/* Project data. Each image: [src, width, height]. */

export const CATEGORIES = [
  { id: 'all', label: 'All' },
  { id: 'direction', label: 'Creative Direction' },
  { id: '3d', label: '3D' },
  { id: 'image', label: 'Image Making' },
  { id: 'production', label: 'Production' },
  { id: 'windows', label: 'Windows Display' },
];

export const PROJECTS = [
  {
    slug: 'coperni-resort-26',
    title: 'Coperni Resort 26',
    client: 'Coperni',
    tag: 'Creative Direction',
    cats: ['direction'],
    year: '2025',
    images: [
      ['images/coperni_resort26.jpg', 1753, 1080],
      ['images/coperni_resort26_2.jpg', 1600, 1067],
      ['images/coperni_resort26_3.jpg', 1600, 1067],
      ['images/coperni_resort26_4.jpg', 768, 1152],
    ],
    desc: 'Campagne marketing Resort 26 pour Coperni, photographiée par Sam Penn. Un univers conceptuel autour du spa et du bien-être, développé en collaboration étroite avec la creative direction de la maison.',
    credits: [
      ['Creative Direction', 'Sébastien Meyer'],
      ['Assistante', 'Alexane Vitte'],
      ['Photographe', 'Sam Penn'],
      ['Styling', 'Helena Tejedor'],
      ['MUA', 'Fay Bio-Toura'],
      ['Hair', 'Clément Billon'],
      ['Set Design', 'Samuel Fasse'],
    ],
  },
  {
    slug: 'coperni-fw25',
    title: 'Coperni Fall Winter 25',
    client: 'Coperni',
    tag: 'Creative Direction',
    cats: ['direction'],
    year: '2025',
    images: [
      ['images/coperni_fw25.jpg', 1754, 1080],
      ['images/coperni_fw25_2.jpg', 1537, 1152],
      ['images/coperni_fw25_3.jpg', 864, 1152],
      ['images/coperni_fw25_4.jpg', 864, 1152],
    ],
    desc: 'Assets marketing Automne-Hiver 25 pour Coperni, photographiés par Gorka Postigo. Concept minimaliste — chambre avec props technologiques, lumière chaude, intérieur épuré.',
    credits: [
      ['Creative Direction', 'Sébastien Meyer'],
      ['Assistante', 'Alexane Vitte'],
      ['Photographe', 'Gorka Postigo'],
      ['Styling', 'Helena Tejedor'],
      ['MUA', 'Victoria Reuter'],
      ['Hair', 'Clément Billon'],
    ],
  },
  {
    slug: 'beau-magazine',
    title: 'Beau Magazine',
    client: 'Beau Magazine',
    tag: 'Creative Direction & 3D Render',
    cats: ['direction', '3d'],
    images: [
      ['images/beau_magazine.jpg', 1756, 1080],
      ['images/beau_magazine_2.jpg', 1280, 1600],
      ['images/beau_magazine_3.jpg', 1280, 1600],
    ],
    desc: "Éditorial pour Beau Magazine fusionnant photographie et CGI. Une réflexion sur la durabilité dans l'image de mode — des décors 3D en open source pour abolir la production physique.",
    credits: [
      ['Creative Direction', 'Alexane Vitte, Zishu Wang, Diane Serfati'],
      ['Photographe', 'Zishu Wang'],
      ['Styling', 'Diane Serfati'],
      ['3D Set Design', 'Alexane Vitte'],
      ['Modèle', 'Amy Lim'],
      ['MUA', 'Shana Montier'],
    ],
  },
  {
    slug: 'loewe-editorial',
    title: 'Loewe — Exit 01: Vuelve',
    client: 'Loewe',
    tag: 'Creative Direction',
    cats: ['direction'],
    cover: ['images/loewe_phone_6.jpg', 2000, 1647],
    images: [
      ['images/loewe_phone_1.jpg', 2000, 1647],
      ['images/loewe_phone_2.jpg', 2000, 1647],
      ['images/loewe_phone_3.jpg', 2000, 1647],
      ['images/loewe_phone_4.jpg', 2000, 1647],
      ['images/loewe_phone_5.jpg', 1333, 2000],
      ['images/loewe_phone_6.jpg', 2000, 1647],
      ['images/loewe_phone_7.jpg', 1333, 2000],
      ['images/loewe_phone_8.jpg', 2000, 1647],
      ['images/loewe_editorial.jpg', 1753, 1080],
      ['images/loewe_2.jpg', 1322, 1089],
      ['images/loewe_3.jpg', 1374, 1132],
      ['images/loewe_4.jpg', 1170, 1466],
      ['images/loewe_5.jpg', 1170, 1466],
    ],
    desc: "Concept éditorial pour Loewe — Exit 01 : Vuelve. Une histoire d'amour à la manière d'Almodóvar, inspirée de « Femmes au bord de la crise de nerfs » (1988).",
    credits: [
      ['Creative Direction', 'Isabel Guedan, Alexane Vitte, Violette Prenant Corric, Zishu Wang'],
      ['Photographe', 'Arturo Ruiz'],
      ['Styling', 'Violette Prenant Corric'],
      ['Modèles', 'Mariana Salaru, Rose Dusser, Auguste P.'],
    ],
  },
  {
    slug: 'acne-diaries',
    title: 'Acne Diaries',
    client: 'Acne Studios',
    tag: 'Creative Direction & Image Making',
    cats: ['direction', 'image'],
    cover: ['images/acne_diaries_cover.jpg', 2000, 1250],
    images: [
      ['images/acne_diaries.jpg', 2000, 829],
      ['images/acne_diaries_2.jpg', 1080, 1350],
      ['images/acne_diaries_3.jpg', 1080, 1350],
      ['images/acne_diaries_4.jpg', 1080, 1350],
      ['images/acne_diaries_5.jpg', 1080, 1350],
      ['images/acne_collage.jpg', 1751, 1080],
      ['images/acne_2.jpg', 1286, 1600],
      ['images/acne_3.jpg', 1418, 1600],
    ],
    desc: 'Concept de campagne pour Acne Studios — un roman graphique visuel. Grille Instagram traitée comme une grille de comics, inspirée de la collection SS24. Composition en fondu enchaîné.',
    credits: [['Creative Direction & Image Making', 'Alexane Vitte']],
  },
  {
    slug: 'blurry-papers',
    title: 'Blurry Papers Magazine',
    client: 'Blurry Papers',
    tag: 'Creative Direction & 3D Render',
    cats: ['direction', '3d'],
    cover: ['images/blurry_cover_selfie.jpg', 1422, 796],
    images: [
      ['images/blurry_papers.jpg', 686, 1080],
      ['images/blurry_2.jpg', 1422, 1600],
      ['images/blurry_3.jpg', 1423, 1600],
    ],
    desc: "Éditorial 3D pour Blurry Papers Magazine — « What's in a girl's bag ? ». Contenu entièrement conçu en 3D, set minimaliste et intérieur.",
    credits: [
      ['Creative Direction', 'Alexane Vitte & Diane Serfati'],
      ['3D Designer', 'Alexane Vitte'],
    ],
  },
  {
    slug: 'shows-shootings',
    title: 'Shows & Shootings',
    client: 'Coperni',
    tag: 'Production & Coordination',
    cats: ['production', 'windows'],
    year: '2023—2026',
    images: [
      ['images/show.jpg', 1752, 1080],
      ['images/show_2.jpg', 999, 1253],
      ['images/show_3.jpg', 1115, 1400],
      ['images/show_4.jpg', 863, 1079],
    ],
    desc: 'Assistante image & production pour les défilés Coperni — FW23, SS25, FW25, SS26. Coordination de shootings, post-production, et mise en scène des vitrines Printemps Paris.',
    credits: [
      ['Défilés', 'FW23 — SS25 — FW25 — SS26'],
      ['Production', 'Production & Post-Production'],
      ['Windows Display', 'Printemps Paris'],
    ],
  },
  {
    slug: 'coperni-fw23-print',
    title: 'Coperni FW23 — Print',
    client: 'Coperni',
    tag: 'AI-Generated Print',
    cats: ['image'],
    year: '2023',
    images: [
      ['images/print_fw23.jpg', 1760, 1080],
      ['images/print_2.jpg', 1600, 800],
      ['images/print_3.jpg', 960, 1440],
      ['images/print_4.jpg', 960, 1440],
    ],
    desc: "Création d'un print généré par intelligence artificielle pour la collection Automne-Hiver 23 de Coperni — « The Wolf and the Lamb ». Pièces ready-to-wear peintes à la main par Gaspar Willmann.",
    credits: [
      ['Collection', 'Coperni Fall Winter 23'],
      ['Print', 'AI-Generated (DALL·E)'],
      ['Peint à la main', 'Gaspar Willmann'],
      ['Porté par', 'Kylie Jenner'],
    ],
  },
];
