/* Project data. Each image: [src, width, height]. */

export const CATEGORIES = [
  { id: 'all', label: 'All' },
  { id: 'direction', label: 'Creative Direction' },
  { id: '3d', label: '3D' },
  { id: 'image', label: 'Image Making' },
  { id: 'production', label: 'Production' },
  { id: 'windows', label: 'Windows Display' },
];

export const PROJECTS = [
  {
    slug: 'acne-diaries',
    title: 'Acne Diaries',
    client: 'Acne Studios',
    tag: 'Creative Direction & Image Making',
    cats: ['direction', 'image'],
    rows: [[0], [1], [2, 3, 4], [5, 6]],
    images: [
      ['images/acne_diaries_cover.jpg', 2000, 1250],
      ['images/acne_diaries.jpg', 2000, 829],
      ['images/acne_diaries_2.jpg', 1080, 1350],
      ['images/acne_diaries_3.jpg', 1080, 1350],
      ['images/acne_diaries_5.jpg', 1080, 1350],
      ['images/acne_diaries_4.jpg', 1080, 1350],
      ['images/acne_2.jpg', 1286, 1600],
    ],
    desc: 'Concept de campagne pour Acne Studios — un roman graphique visuel. Grille Instagram traitée comme une grille de comics, inspirée de la collection SS24. Composition en fondu enchaîné.',
    credits: [['Creative Direction & Image Making', 'Alexane Vitte']],
  },
  {
    slug: 'beau-magazine',
    title: 'Beau Magazine',
    client: 'Beau Magazine',
    tag: 'Creative Direction & 3D Render',
    cats: ['direction', '3d'],
    rows: [[0], [1, 2]],
    images: [
      ['images/beau_magazine.jpg', 1756, 1080],
      ['images/beau_magazine_2.jpg', 1280, 1600],
      ['images/beau_magazine_3.jpg', 1280, 1600],
    ],
    desc: "Éditorial pour Beau Magazine fusionnant photographie et CGI. Une réflexion sur la durabilité dans l'image de mode — des décors 3D en open source pour abolir la production physique.",
    credits: [
      ['Creative Direction', 'Alexane Vitte, Zishu Wang, Diane Serfati'],
      ['Photographe', 'Zishu Wang'],
      ['Styling', 'Diane Serfati'],
      ['3D Set Design', 'Alexane Vitte'],
      ['Modèle', 'Amy Lim'],
      ['MUA', 'Shana Montier'],
    ],
  },
  {
    slug: 'coperni-resort-26',
    title: 'Coperni Resort 26',
    client: 'Coperni',
    tag: 'Creative Direction',
    cats: ['direction'],
    year: '2025',
    rows: [[0], [1, 2, 3, 4], [5, 6, 7, 8]],
    images: [
      ['images/resort26_a.jpg', 2000, 1333],
      ['images/resort26_b.jpg', 1333, 2000],
      ['images/resort26_f.jpg', 768, 1152],
      ['images/resort26_c.jpg', 2000, 1333],
      ['images/resort26_d.jpg', 1333, 2000],
      ['images/resort26_g.jpg', 768, 1152],
      ['images/resort26_e.jpg', 2000, 1333],
      ['images/resort26_h.jpg', 768, 1152],
      ['images/resort26_i.jpg', 768, 1152],
    ],
    desc: 'Campagne marketing Resort 26 pour Coperni, photographiée par Sam Penn. Un univers conceptuel autour du spa et du bien-être, développé en collaboration étroite avec la creative direction de la maison.',
    credits: [
      ['Creative Direction', 'Sébastien Meyer'],
      ['Assistante', 'Alexane Vitte'],
      ['Photographe', 'Sam Penn'],
      ['Styling', 'Helena Tejedor'],
      ['MUA', 'Fay Bio-Toura'],
      ['Hair', 'Clément Billon'],
      ['Set Design', 'Samuel Fasse'],
    ],
  },
  {
    slug: 'coperni-fw25',
    title: 'Coperni Fall Winter 25',
    client: 'Coperni',
    tag: 'Creative Direction',
    cats: ['direction'],
    year: '2025',
    rows: [[0], [1, 2, 3], [4, 5, 6]],
    images: [
      ['images/fw25_a.jpg', 2000, 1499],
      ['images/fw25_b.jpg', 1333, 2000],
      ['images/fw25_c.jpg', 2000, 1499],
      ['images/fw25_d.jpg', 1499, 2000],
      ['images/fw25_e.jpg', 1499, 2000],
      ['images/fw25_f.jpg', 2000, 1499],
      ['images/fw25_g.jpg', 1499, 2000],
    ],
    desc: 'Assets marketing Automne-Hiver 25 pour Coperni, photographiés par Gorka Postigo. Concept minimaliste — chambre avec props technologiques, lumière chaude, intérieur épuré.',
    credits: [
      ['Creative Direction', 'Sébastien Meyer'],
      ['Assistante', 'Alexane Vitte'],
      ['Photographe', 'Gorka Postigo'],
      ['Styling', 'Helena Tejedor'],
      ['MUA', 'Victoria Reuter'],
      ['Hair', 'Clément Billon'],
    ],
  },
  {
    slug: 'loewe-editorial',
    title: 'Loewe — Exit 01: Vuelve',
    client: 'Loewe',
    tag: 'Creative Direction',
    cats: ['direction'],
    rows: [[0], [1, 2, 3], [4, 5, 6, 7], [8, 9]],
    images: [
      ['images/loewe_phone_8.jpg', 2000, 1647],
      ['images/loewe_phone_1.jpg', 2000, 1647],
      ['images/loewe_phone_3.jpg', 2000, 1647],
      ['images/loewe_phone_4.jpg', 2000, 1647],
      ['images/loewe_phone_7.jpg', 1333, 2000],
      ['images/loewe_phone_5.jpg', 1333, 2000],
      ['images/loewe_phone_6.jpg', 2000, 1647],
      ['images/loewe_phone_2.jpg', 2000, 1647],
      ['images/loewe_4.jpg', 1170, 1466],
      ['images/loewe_5.jpg', 1170, 1466],
    ],
    desc: "Concept éditorial pour Loewe — Exit 01 : Vuelve. Une histoire d'amour à la manière d'Almodóvar, inspirée de « Femmes au bord de la crise de nerfs » (1988).",
    credits: [
      ['Creative Direction', 'Isabel Guedan, Alexane Vitte, Violette Prenant Corric, Zishu Wang'],
      ['Photographe', 'Arturo Ruiz'],
      ['Styling', 'Violette Prenant Corric'],
      ['Modèles', 'Mariana Salaru, Rose Dusser, Auguste P.'],
    ],
  },
  {
    slug: 'blurry-papers',
    title: 'Blurry Papers Magazine',
    client: 'Blurry Papers',
    tag: 'Creative Direction & 3D Render',
    cats: ['direction', '3d'],
    cover: ['images/blurry_cover_selfie.jpg', 1422, 796],
    rows: [[0, 1], [2, 3]],
    images: [
      ['images/blurry_cover_white.jpg', 1080, 686],
      ['images/blurry_text.jpg', 1151, 822],
      ['images/blurry_2.jpg', 1422, 1600],
      ['images/blurry_3.jpg', 1423, 1600],
    ],
    desc: "Éditorial 3D pour Blurry Papers Magazine — « What's in a girl's bag ? ». Contenu entièrement conçu en 3D, set minimaliste et intérieur.",
    credits: [
      ['Creative Direction', 'Alexane Vitte & Diane Serfati'],
      ['3D Designer', 'Alexane Vitte'],
    ],
  },
  {
    slug: 'brand-image-communication',
    title: 'Brand Image & Communication',
    client: 'Coperni',
    tag: 'Shooting — Production & Post-Production',
    cats: ['production'],
    year: '2023—2025',
    cover: ['images/brand_cover.jpg', 2000, 1500],
    rows: [[0], [1, 2, 3, 4], [5, 6, 7, 8]],
    images: [
      ['images/brand_shooting_hero.jpg', 2000, 1230, 'Production, Coordination, Post-Production'],
      ['images/brand_shooting_1.jpg', 863, 1079, '[1] Production — Pre Fall 23 shot by Pierre-Ange Carlotti'],
      ['images/brand_shooting_2.jpg', 863, 1078, '[2] Production — Resort 24 shot by Marili Andre - Espace Niemeyer'],
      ['images/brand_shooting_3.jpg', 863, 1079, '[3] Production — Pre Fall 24 shot by Theo Sion - CERN'],
      ['images/brand_shooting_4.jpg', 431, 540, '[4] Production & Post-Production — Pre Fall 25 shot by Stuart Winecoff'],
      ['images/brand_shooting_5.jpg', 863, 1078, '[5] Assistant Production & Post-Production — RBM x Coperni campaign shot by Stuart Winecoff'],
      ['images/brand_shooting_6.jpg', 863, 1078, '[6] Production & Post-Production — Summer campaign shot by Lukasz Pukowiec'],
      ['images/brand_shooting_7.jpg', 863, 1079, '[7] Production & Post-Production — Fall Winter 25 campaign shot by Karim Sadli'],
      ['images/brand_shooting_8.jpg', 863, 1078, '[8] Post-Production — C+ campaign shot by Bettina Pittaluga'],
    ],
    desc: 'Production, coordination et post-production des shootings Coperni : campagnes, lookbooks et assets de marque, de Pre Fall 23 à Fall Winter 25.',
    credits: [
      ['Rôle', 'Production, Coordination & Post-Production'],
      ['Photographes', 'Pierre-Ange Carlotti, Marili Andre, Theo Sion, Stuart Winecoff, Lukasz Pukowiec, Karim Sadli, Bettina Pittaluga'],
    ],
  },
  {
    slug: 'shows-shootings',
    title: 'Brand Image & Communication',
    client: 'Coperni',
    tag: 'Show — Production & Post-Production',
    cats: ['production'],
    year: '2023—2026',
    cover: ['images/show_cover.jpg', 1500, 1200],
    rows: [[0, 1, 2, 3]],
    images: [
      ['images/show_fw23.jpg', 998, 1248, 'Coperni Fall Winter 23 Show — Boston Dynamics Robots choreography'],
      ['images/show_ss25.jpg', 998, 1248, 'Coperni Spring Summer 25 Show — Disneyland Paris'],
      ['images/show_fw25.jpg', 999, 1248, 'Coperni Fall Winter 25 Show — Gamers Lan Party contest'],
      ['images/show_ss26.jpg', 998, 1248, 'Coperni Spring Summer 26 Show'],
    ],
    desc: 'Assistante image & production pour les défilés Coperni — FW23, SS25, FW25, SS26. Coordination de shootings, post-production.',
    credits: [
      ['Défilés', 'FW23 — SS25 — FW25 — SS26'],
      ['Production', 'Production & Post-Production'],
    ],
  },
  {
    slug: 'coperni-fw23-print',
    title: 'Coperni FW23 — Print',
    client: 'Coperni',
    tag: 'AI-Generated Print',
    cats: ['image'],
    year: '2023',
    rows: [[0], [1], [2, 3]],
    images: [
      ['images/print_fw23.jpg', 1760, 1080],
      ['images/print_2.jpg', 1600, 800],
      ['images/print_3.jpg', 960, 1440],
      ['images/print_4.jpg', 960, 1440],
    ],
    desc: "Création d'un print généré par intelligence artificielle pour la collection Automne-Hiver 23 de Coperni — « The Wolf and the Lamb ». Pièces ready-to-wear peintes à la main par Gaspar Willmann.",
    credits: [
      ['Collection', 'Coperni Fall Winter 23'],
      ['Print', 'AI-Generated (DALL·E)'],
      ['Peint à la main', 'Gaspar Willmann'],
      ['Porté par', 'Kylie Jenner'],
    ],
  },
  {
    slug: 'windows-display',
    title: 'Windows Display',
    client: 'Coperni — Printemps Paris',
    tag: 'Production, Set Design & Montage',
    cats: ['windows'],
    cover: ['images/windows_display_cover.jpg', 1024, 768],
    rows: [[0, 1, 2, 3]],
    images: [
      ['images/windows_display_2.jpg', 998, 1248],
      ['images/windows_display_3.jpg', 998, 1248],
      ['images/windows_display_4.jpg', 998, 1248],
      ['images/windows_display_5.jpg', 998, 1248],
    ],
    desc: 'Vitrines Disney × Coperni au Printemps Paris. Production, scénographie et montage de quatre vitrines.',
    credits: [
      ['Lieu', 'Printemps Paris'],
      ['Collaboration', 'Disney × Coperni'],
      ['Mission', 'Production, Set Design & Montage'],
    ],
  },
];
